AWSTemplateFormatVersion: '2010-09-09'
Description: 'S3 bucket for our CICD Pull Request'

Parameters:
  Environment:
    Type: String
    Default: test
    AllowedValues: 
      - test
      - staging
      - production

Resources:
    MyS3Bucket:
      Type: 'AWS::S3::Bucket'
      Properties:
        BucketName: !Sub '${AWS::StackName}-${Environment}-bucket-drw'
        Tags:
          - Key: Environment # Tag key
            Value: !Ref Environment
          - Key: Project
            Value: GithubActionsTesting
  
Outputs:
  BucketName:
    Description: "Name of the created S3 bucket" # Output description
    Value: !Ref MyS3Bucket